In [1]:
#importing libraries
import pandas as pd
import numpy as np
import keras
#import sklearn
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

In [2]:
#importing convulation
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.03
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.70
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.45
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.29

In [3]:


#Check how many point in the data frame, missing values, and genetal information:

concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
#Split the data into target (strength) and (predictors):
concrete_data_columns = concrete_data.columns

In [7]:
target = concrete_data['Strength']
target.head(10)

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
5    47.03
6    43.70
7    36.45
8    45.85
9    39.29
Name: Strength, dtype: float64

In [8]:
predictors = concrete_data.iloc[:, :-1]
predictors.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28

# 

Create a function that defines our regression model for us so that we can conveniently call it to create our model:

    One hidden layer of 10 nodes, and a ReLU activation function
    Use the adam optimizer and the mean squared error as the loss function.

In [9]:
#num of inputs = num of predictors colums
n_cols = predictors.shape[1]
def regression_model():
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [10]:
#Build the model:
model = regression_model()

In [11]:


#Train and test the model at the same time using the fit-method.

list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3)
    #Train and test the model at the same time
    res = model.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 821.9202270507812
Cycle #2: mean_squared_error 202.74154663085938
Cycle #3: mean_squared_error 113.64514923095703
Cycle #4: mean_squared_error 89.14039611816406
Cycle #5: mean_squared_error 71.64591217041016
Cycle #6: mean_squared_error 78.77696990966797
Cycle #7: mean_squared_error 63.331703186035156
Cycle #8: mean_squared_error 65.07695770263672
Cycle #9: mean_squared_error 53.7442741394043
Cycle #10: mean_squared_error 57.193443298339844
Cycle #11: mean_squared_error 57.358646392822266
Cycle #12: mean_squared_error 45.622867584228516
Cycle #13: mean_squared_error 59.52853775024414
Cycle #14: mean_squared_error 56.50010681152344
Cycle #15: mean_squared_error 52.314701080322266
Cycle #16: mean_squared_error 51.464134216308594
Cycle #17: mean_squared_error 48.759788513183594
Cycle #18: mean_squared_error 52.25601577758789
Cycle #19: mean_squared_error 57.43263244628906
Cycle #20: mean_squared_error 51.4804801940918
Cycle #21: mean_squared_error 51.85814666748047
Cycle #22: mean_squared_error 51.24959945678711
Cycle #23: mean_squared_error 62.08351516723633
Cycle #24: mean_squared_error 50.55156326293945
Cycle #25: mean_squared_error 58.30730438232422
Cycle #26: mean_squared_error 58.73436737060547
Cycle #27: mean_squared_error 41.073150634765625
Cycle #28: mean_squared_error 46.658409118652344
Cycle #29: mean_squared_error 52.746986389160156
Cycle #30: mean_squared_error 59.73773956298828
Cycle #31: mean_squared_error 60.42118453979492
Cycle #32: mean_squared_error 49.94325637817383
Cycle #33: mean_squared_error 46.65544128417969
Cycle #34: mean_squared_error 47.678558349609375
Cycle #35: mean_squared_error 48.20378875732422
Cycle #36: mean_squared_error 55.99395751953125
Cycle #37: mean_squared_error 51.861061096191406
Cycle #38: mean_squared_error 51.03480911254883
Cycle #39: mean_squared_error 52.56156921386719
Cycle #40: mean_squared_error 53.163021087646484
Cycle #41: mean_squared_error 48.684688568115234
Cycle #42: mean_squared_error 48.18012619018555
Cycle #43: mean_squared_error 55.450958251953125
Cycle #44: mean_squared_error 49.136295318603516
Cycle #45: mean_squared_error 59.5765495300293
Cycle #46: mean_squared_error 54.11056900024414
Cycle #47: mean_squared_error 49.39280700683594
Cycle #48: mean_squared_error 46.252906799316406
Cycle #49: mean_squared_error 54.10002517700195
Cycle #50: mean_squared_error 46.9134635925293

In [13]:
#Find the mean and the standard deviation of the mean squared errors:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 74.24500617980956
The standard deviation of the mean squared errors: 109.38811741587992

Normalizing the data by substracting the mean and dividing by the standard deviation:

In [14]:
predictors_norm = (predictors - predictors.mean())/predictors.std()
predictors_norm.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069
5,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,0.701883
6,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
7,0.945704,0.244603,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597
8,-0.145138,0.464818,-0.846733,2.174405,-1.038638,-0.526262,-1.291914,-0.279597
9,1.854740,-0.856472,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,-0.279597

In [15]:
#Build the model:
n_cols = predictors_norm.shape[1]
def regression_model2():
    model2 = Sequential()
    model2.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model2.add(Dense(1))
    
    model2.compile(optimizer='adam', loss='mean_squared_error')
    return model2

model2 = regression_model2()

In [16]:
#Train and test the model
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model2.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 661.8780517578125
Cycle #2: mean_squared_error 176.61398315429688
Cycle #3: mean_squared_error 104.37281036376953
Cycle #4: mean_squared_error 79.82703399658203
Cycle #5: mean_squared_error 68.87496185302734
Cycle #6: mean_squared_error 67.62494659423828
Cycle #7: mean_squared_error 63.23350143432617
Cycle #8: mean_squared_error 46.41499328613281
Cycle #9: mean_squared_error 39.40718078613281
Cycle #10: mean_squared_error 42.26898193359375
Cycle #11: mean_squared_error 39.05919647216797
Cycle #12: mean_squared_error 39.55976486206055
Cycle #13: mean_squared_error 36.051368713378906
Cycle #14: mean_squared_error 35.310577392578125
Cycle #15: mean_squared_error 35.88739776611328
Cycle #16: mean_squared_error 31.516054153442383
Cycle #17: mean_squared_error 38.727664947509766
Cycle #18: mean_squared_error 31.4863338470459
Cycle #19: mean_squared_error 30.84206771850586
Cycle #20: mean_squared_error 37.878448486328125
Cycle #21: mean_squared_error 35.69105911254883
Cycle #22: mean_squared_error 27.02437973022461
Cycle #23: mean_squared_error 30.25710105895996
Cycle #24: mean_squared_error 29.4744930267334
Cycle #25: mean_squared_error 32.53895568847656
Cycle #26: mean_squared_error 28.463775634765625
Cycle #27: mean_squared_error 30.02370834350586
Cycle #28: mean_squared_error 35.26320266723633
Cycle #29: mean_squared_error 28.375370025634766
Cycle #30: mean_squared_error 33.207740783691406
Cycle #31: mean_squared_error 32.2713737487793
Cycle #32: mean_squared_error 30.31387710571289
Cycle #33: mean_squared_error 31.63559341430664
Cycle #34: mean_squared_error 31.780149459838867
Cycle #35: mean_squared_error 26.928373336791992
Cycle #36: mean_squared_error 30.446746826171875
Cycle #37: mean_squared_error 33.660011291503906
Cycle #38: mean_squared_error 28.127471923828125
Cycle #39: mean_squared_error 31.36541175842285
Cycle #40: mean_squared_error 30.195880889892578
Cycle #41: mean_squared_error 29.702999114990234
Cycle #42: mean_squared_error 31.78091812133789
Cycle #43: mean_squared_error 26.531831741333008
Cycle #44: mean_squared_error 26.747724533081055
Cycle #45: mean_squared_error 27.411396026611328
Cycle #46: mean_squared_error 25.48451805114746
Cycle #47: mean_squared_error 31.097688674926758
Cycle #48: mean_squared_error 26.078418731689453
Cycle #49: mean_squared_error 21.417909622192383
Cycle #50: mean_squared_error 32.0643310546875

In [17]:
#The mean and the standard deviation of the mean squared errors:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 52.043954620361326
The standard deviation of the mean squared errors: 90.52259822871025

The mean and the standard deviation of the mean squared errors in case A is more than in case B. But the difference is tiny.
Therefore the error is huge.

Train and test the model at the same time using the fit-method. We will leave out 30% of the data (data after normalization) for validation and we will train the model for 100 epochs instead of 50 epochs.

Part C:Build the model:

In [18]:
def regression_model3():
    model3 = Sequential()
    model3.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model3.add(Dense(1))
    
    model3.compile(optimizer='adam', loss='mean_squared_error')
    return model3

model3 = regression_model3()

In [19]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model3.fit(X_train, y_train, epochs=100, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 164.16368103027344
Cycle #2: mean_squared_error 93.18791198730469
Cycle #3: mean_squared_error 75.426025390625
Cycle #4: mean_squared_error 72.98502349853516
Cycle #5: mean_squared_error 50.93279266357422
Cycle #6: mean_squared_error 51.785552978515625
Cycle #7: mean_squared_error 44.291046142578125
Cycle #8: mean_squared_error 47.054725646972656
Cycle #9: mean_squared_error 37.69520568847656
Cycle #10: mean_squared_error 36.9311408996582
Cycle #11: mean_squared_error 37.5770263671875
Cycle #12: mean_squared_error 39.579132080078125
Cycle #13: mean_squared_error 37.26737594604492
Cycle #14: mean_squared_error 38.88407897949219
Cycle #15: mean_squared_error 36.224945068359375
Cycle #16: mean_squared_error 40.76089859008789
Cycle #17: mean_squared_error 33.40694046020508
Cycle #18: mean_squared_error 37.13996124267578
Cycle #19: mean_squared_error 36.107505798339844
Cycle #20: mean_squared_error 36.11727523803711
Cycle #21: mean_squared_error 34.386898040771484
Cycle #22: mean_squared_error 30.339237213134766
Cycle #23: mean_squared_error 36.251380920410156
Cycle #24: mean_squared_error 39.63508224487305
Cycle #25: mean_squared_error 39.17427062988281
Cycle #26: mean_squared_error 39.035614013671875
Cycle #27: mean_squared_error 34.824363708496094
Cycle #28: mean_squared_error 35.64306640625
Cycle #29: mean_squared_error 35.50030517578125
Cycle #30: mean_squared_error 39.38386535644531
Cycle #31: mean_squared_error 38.085880279541016
Cycle #32: mean_squared_error 38.713008880615234
Cycle #33: mean_squared_error 36.11000061035156
Cycle #34: mean_squared_error 36.3935661315918
Cycle #35: mean_squared_error 32.91020202636719
Cycle #36: mean_squared_error 32.698692321777344
Cycle #37: mean_squared_error 29.900434494018555
Cycle #38: mean_squared_error 37.36248016357422
Cycle #39: mean_squared_error 36.037967681884766
Cycle #40: mean_squared_error 36.49767303466797
Cycle #41: mean_squared_error 30.89234161376953
Cycle #42: mean_squared_error 33.90216064453125
Cycle #43: mean_squared_error 31.456972122192383
Cycle #44: mean_squared_error 32.12922668457031
Cycle #45: mean_squared_error 31.59403419494629
Cycle #46: mean_squared_error 36.64468002319336
Cycle #47: mean_squared_error 35.33984375
Cycle #48: mean_squared_error 31.82223129272461
Cycle #49: mean_squared_error 35.968780517578125
Cycle #50: mean_squared_error 40.57815170288086

To find the mean and the standard deviation of the mean squared errors:

In [20]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 42.13461315155029
The standard deviation of the mean squared errors: 20.850281154943957

The mean and the standard deviation of the mean squared errors in case B is bigger than in case C. But in both cases error is huge.

Part D:Create a new model with three hidden layers, each of 10 nodes and ReLU activation function.

In [21]:
def regression_model4():
    model4 = Sequential()
    model4.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model4.add(Dense(10, activation='relu'))
    model4.add(Dense(10, activation='relu'))
    model4.add(Dense(1))
    
    model4.compile(optimizer='adam', loss='mean_squared_error')
    return model4

Build a new model with 3 hidden layers:

In [22]:
model4 = regression_model4()

Train and test the model at the same time using the fit-method. We will leave out 30% of the data (data after normalization) for validation and we will train the model for 50 epochs and use three hidden layers, each of 10 nodes and ReLU activation function.

In [23]:
list_of_mean_squared_error = []
for cycle in range(50):
    #Randomly split the data into a training set (70%) and a test set (30%):  
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)
    #Train and test the model at the same time
    res = model4.fit(X_train, y_train, epochs=50, verbose=0, validation_data=(X_test, y_test))
    #Find mean_squared_error as last value in history.
    mean_squared_error = res.history['val_loss'][-1]
    #Add value of mean_squared_error for every cycle in list.
    list_of_mean_squared_error.append(mean_squared_error)
    print('Cycle #{}: mean_squared_error {}'.format(cycle+1, mean_squared_error))

Cycle #1: mean_squared_error 121.1694107055664
Cycle #2: mean_squared_error 95.87380981445312
Cycle #3: mean_squared_error 68.10939025878906
Cycle #4: mean_squared_error 47.249595642089844
Cycle #5: mean_squared_error 41.6532096862793
Cycle #6: mean_squared_error 35.27151107788086
Cycle #7: mean_squared_error 39.003517150878906
Cycle #8: mean_squared_error 32.67680358886719
Cycle #9: mean_squared_error 41.63198471069336
Cycle #10: mean_squared_error 33.549686431884766
Cycle #11: mean_squared_error 35.726593017578125
Cycle #12: mean_squared_error 36.827030181884766
Cycle #13: mean_squared_error 29.495988845825195
Cycle #14: mean_squared_error 33.539005279541016
Cycle #15: mean_squared_error 35.74142837524414
Cycle #16: mean_squared_error 33.94647979736328
Cycle #17: mean_squared_error 30.17803382873535
Cycle #18: mean_squared_error 26.61604881286621
Cycle #19: mean_squared_error 30.136953353881836
Cycle #20: mean_squared_error 29.534381866455078
Cycle #21: mean_squared_error 30.14904022216797
Cycle #22: mean_squared_error 31.632802963256836
Cycle #23: mean_squared_error 32.107688903808594
Cycle #24: mean_squared_error 26.08755874633789
Cycle #25: mean_squared_error 30.212697982788086
Cycle #26: mean_squared_error 31.794023513793945
Cycle #27: mean_squared_error 27.93049430847168
Cycle #28: mean_squared_error 30.492311477661133
Cycle #29: mean_squared_error 29.6151180267334
Cycle #30: mean_squared_error 26.645858764648438
Cycle #31: mean_squared_error 26.340299606323242
Cycle #32: mean_squared_error 23.637340545654297
Cycle #33: mean_squared_error 20.170604705810547
Cycle #34: mean_squared_error 24.424304962158203
Cycle #35: mean_squared_error 25.94819450378418
Cycle #36: mean_squared_error 24.515588760375977
Cycle #37: mean_squared_error 23.228313446044922
Cycle #38: mean_squared_error 22.3388614654541
Cycle #39: mean_squared_error 24.744850158691406
Cycle #40: mean_squared_error 28.67605972290039
Cycle #41: mean_squared_error 24.37853240966797
Cycle #42: mean_squared_error 28.686548233032227
Cycle #43: mean_squared_error 27.122177124023438
Cycle #44: mean_squared_error 30.378236770629883
Cycle #45: mean_squared_error 22.372772216796875
Cycle #46: mean_squared_error 25.871057510375977
Cycle #47: mean_squared_error 26.56195640563965
Cycle #48: mean_squared_error 25.526775360107422
Cycle #49: mean_squared_error 21.5079288482666
Cycle #50: mean_squared_error 29.319351196289062

Finding the mean and the standard deviation of the mean squared errors:

In [24]:
print('The mean of the mean squared errors: {}'.format(np.mean(list_of_mean_squared_error)))
print('The standard deviation of the mean squared errors: {}'.format(np.std(list_of_mean_squared_error)))

The mean of the mean squared errors: 33.60696422576904
The standard deviation of the mean squared errors: 17.278741007708376

The mean and the standard deviation of the mean squared errors in case D is less than in case A, B and C. And it's the only case where error is not very big. It means additional layers in neural network are helping and is an important factor to detect error.